### ISSUE TITLE
Error: Unable to access jarfile GenomeAnalysisTK.jar

### ISSUE THREAD

**Issue by ospupegam** [mr-eyes/nu-ngs01#1]
https://gatkforums.broadinstitute.org/gatk/discussion/11816/there-is-no-genomeanalysistk-jar-file-in-gatk-package

"The Indel Realignment steps have been removed from the Best Practices, so you won't find those tools in GATK4."

**Comment by mr-eyes** [comment]
Just copying pasting the solution from another issue.

> solved by :
> https://software.broadinstitute.org/gatk/documentation/tooldocs/4.1.2.0/org_broadinstitute_hellbender_tools_walkers_rnaseq_SplitNCigarReads.php
